beclab/docs

docs/developer/develop/package/manifest.md
docs/developer/develop/tutorial/note/create.md

Add new fields description in TerminusManifest, and add some detailed info. 
Add install step in devbox tutorial since it has to be installed from market now.

doc: add TerminusManifest fields and add devbox install tips

---

docs/developer/develop/advanced/cli.md
docs/how-to/terminus/setup/install/linux.md
docs/how-to/terminus/setup/install/mac.md
docs/how-to/terminus/setup/install/raspberry.md
docs/how-to/terminus/setup/install/windows.md
docs/overview/introduction/getting-started/index.md
docs/overview/introduction/getting-started/linux.md
docs/overview/introduction/getting-started/mac.md
docs/overview/introduction/getting-started/raspberry.md
docs/overview/introduction/getting-started/windows.md
docs/overview/introduction/what-is-terminus.md
docs/overview/protocol/market.md

Includes follow-up optimizations and fixes for the installation guides update

follow-up fixes and updates for installation guides and related files

---

docs/how-to/terminus/index.md
docs/how-to/terminus/setup/install/mac.md
docs/how-to/terminus/setup/install/raspberry.md
docs/how-to/terminus/setup/install/windows.md
docs/overview/introduction/getting-started/index.md
docs/overview/introduction/getting-started/mac.md
docs/overview/introduction/getting-started/raspberry.md
docs/overview/introduction/getting-started/windows.md
docs/overview/introduction/what-is-terminus.md

1. Refine Terminus overview opening 
2. Replace more Terminus OS instances in key documents
3. Update Raspberry system support info and related steps

Update Raspberry system info and Terminus wording

---

docs/developer/develop/advanced/provider.md
docs/developer/develop/package/manifest.md

- update sections about service provider
- add OIDC field description in TerminusManifest.yaml

feat: update provider sections and OIDC

---

docs/developer/develop/advanced/terminus-info.md

Added the missing `/api/` in API call address.

fix api call URL error

---

docs/developer/develop/package/manifest.md

Add new authLevel vaule internal
Change spec>language to spec>locale and support i18n

feat: add authLevel internal and i18n related content

---

docs/zh/how-to/termipass/account/index.md
docs/zh/overview/terminus/terminus-name.md

Do not merge unless https://github.com/beclab/docs/pull/51 is merged, and the new process is officially released.

i18n: update terminus name creation process

---

docs/developer/develop/package/chart.md
docs/developer/develop/package/manifest.md

add udp section in manifest
fix chart directory structure

add udp section in manifest and fix chart directory structure

---

docs/manual/get-started/create-olares-id.md
docs/manual/get-started/install-olares.md

This PR adds a note to direct users from mainland china to read simplifed Chinese version.

chore: add note for mainland china users

---

docs/manual/get-started/install-olares-linux.md
docs/zh/manual/get-started/install-olares-linux.md

This PR upadates ubuntu version from `22.04` to `20.04` for linux installation.

fix: update ubuntu version requirement for linux

---

docs/zh/manual/get-started/install-olares-windows.md

chore: update script download URL for windows install in cn

---

docs/manual/get-started/install-olares-lxc.md
docs/zh/manual/get-started/install-olares-lxc.md

chore: fix LXC config in install scripts

---

docs/manual/concepts/network.md
docs/zh/manual/concepts/network.md

This PR adds missing internal entrance description

fix: add missing internal entrance description

---

docs/.vitepress/zh.ts
docs/manual/get-started/next-steps.md
docs/manual/use-cases/index.md
docs/zh/manual/get-started/next-steps.md
docs/zh/manual/use-cases/index.md

chore: fix cn doc switch issue

---

docs/.vitepress/en.ts
docs/.vitepress/zh.ts
docs/developer/install/cli/gpu.md
docs/zh/developer/install/cli/gpu.md
docs/zh/developer/install/cli/olares-change-ip.md
docs/zh/developer/install/cli/olares-cli.md
docs/zh/developer/install/cli/olares-release.md
docs/zh/developer/install/cli/olares-uninstall.md
docs/zh/developer/install/installation-process.md

feat: add gpu command reference

---

docs/manual/space/manage-olares.md
docs/zh/manual/space/manage-olares.md

This PR updates a wrong link for Olares Space.

fix: update link for Olares Space

---

docs/developer/develop/package/manifest.md
docs/zh/developer/develop/package/manifest.md

add description for `runAsUser` and improve the doc format
add tailscaleAcls section
update chinese version

add item for runAsUser and acl

---

package-lock.json
package.json

This PR:
- modifies package-lock.json and removes node_modules

fix: docs search display

---

docs/manual/tasks/update.md
docs/zh/manual/tasks/update.md

This PR:
- updates the olaresd shell script name for v.1.11.6

feat: update olaresd shell script name for v.1.11.6

---

docs/manual/use-cases/dify.md
docs/zh/manual/use-cases/dify.md

This PR:
- updates download description for Dify.
- adds a note to instruct users to uninstall “Dify For Cluster” and “Dify” after they upgrading to v1.11.6.

feat: update dify download description

---

docs/developer/install/additional-installations.md
docs/manual/get-started/install-olares.md

chore: fix markdown format issues

---

docs/manual/tutorials/stream-game.md
docs/zh/manual/tutorials/stream-game.md

chore: fix steam command error

---

docs/.vitepress/en.ts
docs/.vitepress/zh.ts
docs/developer/install/index.md
docs/manual/get-started/install-olares-linux.md
docs/manual/get-started/install-olares.md
docs/zh/developer/install/index.md
docs/zh/manual/get-started/install-olares-linux.md
docs/zh/manual/get-started/install-olares.md

chore: hide other installation methods
